import Link from 'next/link';

export const metadata = { title: 'Privacy Policy | Neighborly KC', description: 'Neighborly KC Privacy Policy' };

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#f0f6ff] text-[#00205a]">
    <header className="bg-[#004687] text-white px-5 py-5">
      <div className="max-w-3xl mx-auto flex items-center justify-between gap-4">
        <Link href="/" className="font-black text-xl">Neighborly KC</Link>
        <Link href="/" className="text-sm underline underline-offset-4">Back to Neighborly KC</Link>
      </div>
    </header>
    <article className="max-w-3xl mx-auto px-5 py-10 bg-white min-h-screen">
      <h1 className="text-3xl font-black">Privacy Policy</h1><p className="text-sm opacity-60 mt-2">Effective Date: August 14, 2026</p>
      <Section title="1. Information We Collect"><p>When you use Neighborly KC, we may collect information you provide, including your name, email address, neighborhood and ZIP code, profile information, photos, posts, comments, likes, direct messages, feedback, and information you provide when contacting us.</p><h3>Google Sign-In</h3><p>If you sign in with Google, Neighborly KC receives information necessary to authenticate your account, which may include your Google account name, email address, profile picture, and account identifiers. We do not receive or store your Google password. Google account information is used to create and maintain your Neighborly KC account, authenticate you, and provide Neighborly KC features. We do not sell Google user data or use it for advertising.</p><p>We may also collect limited technical information such as IP address, browser type, device type, operating system, and information needed to operate and secure the service.</p></Section>
      <Section title="2. How We Use Information"><p>We use information to create and maintain accounts, authenticate users, verify neighborhood membership, provide community features, display posts and profiles, enable comments, likes and messaging, send account and activity notifications, respond to feedback, detect spam and abuse, protect the service, improve Neighborly KC, and comply with applicable law.</p></Section>
      <Section title="3. Information Visible to Other Members"><p>Neighborly KC is a community platform. Information you voluntarily publish may be visible to other members, including your display name, neighborhood, profile information, posts, comments, photos, reactions, and other information you include in public content. Please do not publish sensitive personal information you do not want other members to see. Direct messages are intended to remain private between participants, subject to operation of the service and applicable law.</p></Section>
      <Section title="4. Location and Neighborhood Information"><p>We may use your ZIP code, neighborhood, city, or neighborhood verification information to provide location-based community features. We do not intend to publicly display your precise home address as part of normal public profile or post viewing unless you voluntarily include it in content you publish.</p></Section>
      <Section title="5. Photos and User Content"><p>You retain ownership of content you create and upload. By uploading content to Neighborly KC, you give us the limited permission necessary to store, process, display, and distribute that content as part of providing the service. You are responsible for ensuring that content you upload does not violate another person's privacy, copyright, or other rights.</p></Section>
      <Section title="6. Email Notifications"><p>Neighborly KC may send emails about activity on your account, including reactions to your posts, account activity, security, or other features you use. We may use third-party email delivery providers to send these messages.</p></Section>
      <Section title="7. Third-Party Services"><p>Neighborly KC may use third-party services for authentication, database and application infrastructure, hosting, email delivery, security, and abuse prevention. These providers may process information as necessary to provide their services. We do not sell your personal information.</p></Section>
      <Section title="8. Data Security"><p>We use reasonable technical and organizational safeguards intended to protect information from unauthorized access, alteration, disclosure, or destruction. No internet service can guarantee complete security.</p></Section>
      <Section title="9. Data Retention"><p>We generally retain account and content information for as long as reasonably necessary to provide the service, maintain security, resolve disputes, comply with legal requirements, and enforce our agreements. When information is no longer reasonably necessary, we may delete or anonymize it, subject to backups, technical limitations, and legal requirements.</p></Section>
      <Section title="10. Your Choices"><p>Depending on available features, you may update your profile, edit or delete your posts, change preferences, stop using Neighborly KC, or request access, correction, or deletion of certain personal information. Some information may need to be retained for security, fraud prevention, legal compliance, or other legitimate purposes.</p></Section>
      <Section title="11. Children's Privacy"><p>Neighborly KC is not directed toward children under 13. We do not knowingly collect personal information from children under 13.</p></Section>
      <Section title="12. Changes to This Policy"><p>We may update this Privacy Policy as Neighborly KC develops or as legal requirements change. Material changes may be communicated through the service or another appropriate method. The Effective Date indicates the current version.</p></Section>
      <Section title="13. Contact"><p>For privacy questions or requests, contact Neighborly KC through the contact information provided on the website.</p></Section>
    </article>
  </main>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8"><h2 className="text-xl font-black">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 opacity-85">{children}</div></section>}
