import Link from 'next/link';
export const metadata = { title: 'Terms of Service | Neighborly KC', description: 'Neighborly KC Terms of Service' };
export default function TermsPage(){return <main className="min-h-screen bg-[#f0f6ff] text-[#00205a]"><header className="bg-[#004687] text-white px-5 py-5"><div className="max-w-3xl mx-auto flex items-center justify-between gap-4"><Link href="/" className="font-black text-xl">Neighborly KC</Link><Link href="/" className="text-sm underline underline-offset-4">Back to Neighborly KC</Link></div></header><article className="max-w-3xl mx-auto px-5 py-10 bg-white min-h-screen"><h1 className="text-3xl font-black">Terms of Service</h1><p className="text-sm opacity-60 mt-2">Effective Date: August 14, 2026</p>
<Section title="1. About Neighborly KC"><p>Neighborly KC is a community platform designed to help neighbors connect, share information, communicate, and participate in local conversations. Features may include neighborhood feeds, posts, comments, photos, reactions, direct messages, notifications, profiles, and other community tools.</p></Section>
<Section title="2. Accounts"><p>You are responsible for maintaining the security of your account and for activity that occurs through it. You agree to provide accurate information and keep it reasonably current. You may sign in using supported authentication providers, including Google. You may not use another person's account without permission.</p></Section>
<Section title="3. Community Standards"><p>You agree not to use Neighborly KC to harass, threaten, stalk, or intimidate others; post fraudulent or intentionally misleading information; impersonate another person; share another person's private information without permission; post illegal content; promote violence; distribute spam or malicious content; bypass security or moderation systems; interfere with the service; violate another person's rights; or upload content that infringes intellectual property rights.</p></Section>
<Section title="4. User Content"><p>You are responsible for content you post or upload. You retain ownership of your original content. By posting or uploading content to Neighborly KC, you grant Neighborly KC a non-exclusive, worldwide, royalty-free license to host, store, reproduce, display, and distribute that content as necessary to operate and provide the service. This license ends when the content is deleted, except where retention is reasonably necessary for backups, security, legal compliance, or legitimate operations.</p></Section>
<Section title="5. Photos"><p>Only upload photographs that you have permission to share. Do not use Neighborly KC to publish private images or personal information belonging to another person without appropriate permission.</p></Section>
<Section title="6. Direct Messages"><p>Neighborly KC may provide private messaging between members. You are responsible for messages you send and may not use messaging to harass, threaten, scam, impersonate, or abuse another member.</p></Section>
<Section title="7. Moderation and Safety"><p>Neighborly KC may use automated and manual systems to detect spam, abuse, fraudulent behavior, or violations of these Terms. We may remove content, limit features, suspend accounts, or take other reasonable action to protect the community or service. We may cooperate with law enforcement or other authorities when legally required.</p></Section>
<Section title="8. Feedback"><p>If you submit feedback, suggestions, ideas, or other comments about Neighborly KC, you agree that we may use that feedback to improve the service without owing you compensation.</p></Section>
<Section title="9. Third-Party Services"><p>Neighborly KC may rely on third-party services for authentication, hosting, database infrastructure, email delivery, security, and other functionality. Your use of those services may also be subject to their own terms and policies.</p></Section>
<Section title="10. Availability"><p>We work to keep Neighborly KC available and reliable, but we do not guarantee that the service will always be uninterrupted, error-free, or available. We may temporarily suspend or modify the service for maintenance, security, upgrades, or other reasons.</p></Section>
<Section title="11. Account Suspension or Termination"><p>You may stop using Neighborly KC at any time. We may suspend or terminate accounts that violate these Terms, threaten community safety, compromise the service, or create legal or security risks. We may also suspend accounts when necessary to investigate suspected abuse or fraud.</p></Section>
<Section title="12. Intellectual Property"><p>Neighborly KC's software, branding, design, logos, graphics, and other original materials are owned by or licensed to Neighborly KC unless otherwise indicated. You may not copy, modify, distribute, sell, or commercially exploit proprietary materials without permission.</p></Section>
<Section title="13. Disclaimer"><p>Neighborly KC provides a platform for community interaction. We do not guarantee the accuracy, reliability, or completeness of information posted by users. Users are responsible for evaluating information shared by other members. Neighborly KC does not endorse statements made by individual users.</p></Section>
<Section title="14. Limitation of Liability"><p>To the extent permitted by applicable law, Neighborly KC and its operators will not be responsible for indirect, incidental, consequential, special, or punitive damages arising from your use of or inability to use the service. Nothing in these Terms is intended to exclude liability that cannot legally be excluded.</p></Section>
<Section title="15. Indemnification"><p>To the extent permitted by law, you agree to be responsible for claims, losses, liabilities, and expenses arising from your violation of these Terms or misuse of Neighborly KC.</p></Section>
<Section title="16. Changes to These Terms"><p>We may update these Terms as the service develops. If material changes are made, we may provide notice through Neighborly KC or another appropriate method. Continued use after an updated version becomes effective means you accept the updated Terms.</p></Section>
<Section title="17. Governing Law"><p>These Terms are governed by applicable laws of the State of Missouri, without regard to conflict-of-law principles, except where applicable law requires otherwise.</p></Section>
<Section title="18. Contact"><p>Questions about these Terms may be sent through the contact information provided on the Neighborly KC website.</p></Section>
</article></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8"><h2 className="text-xl font-black">{title}</h2><div className="mt-3 text-sm leading-7 opacity-85">{children}</div></section>}
