'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { supabase, displayName } from '../../../lib/community';
export default function ProfilePage(){
 const params=useParams<{id:string}>(); const id=params.id; const [p,setP]=useState<any>(null),[posts,setPosts]=useState<any[]>([]),[me,setMe]=useState<any>(null),[conn,setConn]=useState<any>(null),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const {data:{user}}=await supabase.auth.getUser();setMe(user);const {data:pr}=await supabase.from('profiles').select('auth_user_id,full_name,email,zip,street_address').eq('auth_user_id',id).maybeSingle();setP(pr);const {data:po}=await supabase.from('posts').select('id,body,category,created_at,image_url,neighborhood_id').eq('user_id',id).order('created_at',{ascending:false}).limit(20);setPosts(po||[]);if(user&&user.id!==id){const {data:c}=await supabase.from('connections').select('*').or(`and(requester_id.eq.${user.id},addressee_id.eq.${id}),and(requester_id.eq.${id},addressee_id.eq.${user.id})`).maybeSingle();setConn(c)}setLoading(false)};
 useEffect(()=>{load()},[id]);
 const connect=async()=>{if(!me)return window.location.href='/';await supabase.from('connections').insert({requester_id:me.id,addressee_id:id,status:'pending'});await load()};
 if(loading)return <main className="min-h-screen grid place-items-center bg-[#f2eadc]">Loading…</main>;
 if(!p)return <main className="min-h-screen grid place-items-center bg-[#f2eadc]">Neighbor not found.</main>;
 const status=conn?.status;
 return <main className="min-h-screen bg-[#f2eadc] text-[#1a3a2f]"><header className="bg-[#1a3a2f] text-white p-4"><div className="max-w-3xl mx-auto"><Link href="/people" className="text-xs opacity-70">← People</Link></div></header><div className="max-w-3xl mx-auto p-4 space-y-4"><section className="rounded-3xl bg-white border border-[#e5d9c5] p-6"><div className="flex flex-col sm:flex-row gap-5 items-start"><div className="w-20 h-20 rounded-full bg-[#e8e0d0] grid place-items-center text-3xl font-black">{displayName(p).slice(0,1).toUpperCase()}</div><div className="flex-1"><h1 className="text-3xl font-black">{displayName(p)}</h1><p className="opacity-60">📍 Kansas City {p.zip?`• ${p.zip}`:''}</p><p className="text-sm mt-3 opacity-70">Neighborly KC member</p></div>{me?.id!==id&&<div className="flex gap-2">{status==='accepted'?<span className="rounded-full border px-4 py-2 font-bold">Connected</span>:status==='pending'&&conn?.requester_id===me?.id?<span className="rounded-full bg-[#f1ede6] px-4 py-2 font-bold">Pending</span>:status==='pending'?<Link href="/connections" className="rounded-full bg-[#1a3a2f] text-white px-4 py-2 font-bold">Respond</Link>:<button onClick={connect} className="rounded-full bg-[#1a3a2f] text-white px-4 py-2 font-bold">Connect</button>}<Link href={`/dms?user=${id}`} className="rounded-full border px-4 py-2 font-bold">Message</Link></div>}</div><div className="grid grid-cols-2 gap-3 mt-6"><div className="rounded-2xl bg-[#f1ede6] p-4"><b>{posts.length}</b><p className="text-xs opacity-60">Posts</p></div><div className="rounded-2xl bg-[#f1ede6] p-4"><b>{status==='accepted'?1:0}</b><p className="text-xs opacity-60">Connection</p></div></div></section><section><h2 className="font-black text-xl mb-3">Recent posts</h2>{!posts.length?<div className="rounded-2xl bg-white p-8 text-center opacity-60">No posts yet.</div>:posts.map(x=><article key={x.id} className="rounded-2xl bg-white border border-[#e5d9c5] p-4 mb-3"><p className="text-xs font-bold opacity-60">{x.category}</p><p className="mt-1 whitespace-pre-wrap">{x.body}</p>{x.image_url&&<img src={x.image_url} alt="post" className="mt-3 rounded-xl max-h-96 w-full object-cover"/>}<p className="text-xs opacity-40 mt-3">{new Date(x.created_at).toLocaleString()}</p></article>)}</section></div></main>
}
