'use client';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { supabase, displayName } from '../../lib/community';

function DmsContent(){
 const params=useSearchParams(); const target=params.get('user');
 const [me,setMe]=useState<any>(null),[people,setPeople]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[selected,setSelected]=useState<string|null>(target),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false);
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();setMe(user);if(!user){setLoading(false);return;}const {data:p}=await supabase.from('profiles').select('auth_user_id,full_name,email,zip').not('auth_user_id','is',null).neq('auth_user_id',user.id).order('full_name');setPeople(p||[]);setLoading(false)};
 const loadMessages=async(id:string)=>{if(!me)return;setSelected(id);const {data}=await supabase.from('dms').select('*').or(`and(from_user_id.eq.${me.id},to_user_id.eq.${id}),and(from_user_id.eq.${id},to_user_id.eq.${me.id})`).order('created_at',{ascending:true});setMessages(data||[])};
 useEffect(()=>{load()},[]); useEffect(()=>{if(me&&target)loadMessages(target)},[me,target]);
 useEffect(()=>{if(!me)return;const ch=supabase.channel('nkc-dms').on('postgres_changes',{event:'INSERT',schema:'public',table:'dms'},payload=>{const m:any=payload.new;if((m.from_user_id===me.id&&m.to_user_id===selected)||(m.to_user_id===me.id&&m.from_user_id===selected))setMessages(x=>[...x,m])}).subscribe();return()=>{supabase.removeChannel(ch)}},[me,selected]);
 const current=useMemo(()=>people.find(p=>p.auth_user_id===selected),[people,selected]);
 const send=async()=>{if(!me||!selected||!text.trim())return;setSending(true);const message=text.trim();const {data,error}=await supabase.from('dms').insert({from_user_id:me.id,to_user_id:selected,message,body:message}).select().single();if(error)alert(error.message);else{setMessages(x=>[...x,data]);setText('')}setSending(false)};
 if(loading)return <main className="min-h-screen grid place-items-center bg-[#f0f6ff]">Loading…</main>;
 if(!me)return <main className="min-h-screen grid place-items-center bg-[#f0f6ff]"><div className="text-center"><p className="font-bold">Sign in to use Messages.</p><Link href="/" className="underline">Back to Neighborly KC</Link></div></main>;
 return <main className="min-h-screen bg-[#f0f6ff] text-[#00205a]"><header className="bg-[#004687] text-white p-4"><div className="max-w-4xl mx-auto flex justify-between items-center"><div><Link href="/" className="text-xs opacity-70">← Feed</Link><h1 className="font-black text-2xl">Messages</h1></div><Link href="/people" className="rounded-full bg-white text-[#004687] px-4 py-2 text-sm font-bold">Find People</Link></div></header><div className="max-w-4xl mx-auto p-4 grid md:grid-cols-[280px_1fr] gap-4"><aside className="rounded-2xl bg-white border border-[#c2d5f0] p-3"><p className="text-xs font-bold opacity-50 px-2 pb-2">NEIGHBORS</p>{!people.length?<p className="p-3 text-sm opacity-50">No other members yet.</p>:people.map(p=><button key={p.auth_user_id} onClick={()=>loadMessages(p.auth_user_id)} className={`w-full text-left rounded-xl p-3 ${selected===p.auth_user_id?'bg-[#004687] text-white':'hover:bg-[#e6eefb]'}`}><b className="block text-sm">{displayName(p)}</b><span className="text-xs opacity-60">Kansas City{p.zip?` • ${p.zip}`:''}</span></button>)}</aside><section className="rounded-2xl bg-white border border-[#c2d5f0] min-h-[520px] flex flex-col">{selected?<><div className="p-4 border-b border-[#c2d5f0]"><Link href={`/profile/${selected}`} className="font-black hover:underline">{displayName(current)}</Link><p className="text-xs opacity-50">Private conversation</p></div><div className="flex-1 p-4 space-y-2 overflow-y-auto">{messages.map(m=><div key={m.id} className={`flex ${m.from_user_id===me.id?'justify-end':''}`}><div className={`max-w-[75%] rounded-2xl px-4 py-2 ${m.from_user_id===me.id?'bg-[#004687] text-white':'bg-[#e6eefb]'}`}><p>{m.message||m.body}</p><p className="text-[10px] opacity-50 mt-1">{new Date(m.created_at).toLocaleString()}</p></div></div>)}{!messages.length&&<p className="text-center opacity-40 py-16">Start the conversation.</p>}</div><div className="p-3 border-t border-[#c2d5f0] flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder={`Message ${displayName(current)}...`} className="flex-1 rounded-full border border-[#c2d5f0] px-4 py-3 outline-none"/><button disabled={sending} onClick={send} className="rounded-full bg-[#004687] text-white px-5 font-bold">{sending?'...':'Send'}</button></div></>:<div className="flex-1 grid place-items-center p-10 text-center opacity-50">Select a neighbor to start a conversation.</div>}</section></div></main>;
}

export default function DmsPage(){
  return <Suspense fallback={<main className="min-h-screen grid place-items-center bg-[#f0f6ff] text-[#00205a]">Loading…</main>}><DmsContent /></Suspense>;
}
